services:
  golf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golf
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      DATABASE_URL: "postgresql://golfapp:changeme@host.docker.internal:5432/golfdb"
      NODE_ENV: "production"
      HOSTNAME: "0.0.0.0"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
